// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhkKXxts4_FmdJBZBLKpDE4DV7DsPPZkM',
    appId: '1:146150107054:web:15ffcbed7e15927ea28a3f',
    messagingSenderId: '146150107054',
    projectId: 'lina-ad203',
    authDomain: 'lina-ad203.firebaseapp.com',
    storageBucket: 'lina-ad203.firebasestorage.app',
    measurementId: 'G-7HP89ZRMVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqAkMHWzUkVGWKKJ0dJ66z-Kl5GC_F0dk',
    appId: '1:146150107054:android:45a554ecf50cb042a28a3f',
    messagingSenderId: '146150107054',
    projectId: 'lina-ad203',
    storageBucket: 'lina-ad203.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFmF55dt5LNIY6sCFfcvrkpKFVpo2L2_M',
    appId: '1:146150107054:ios:2de9c8c247968eb9a28a3f',
    messagingSenderId: '146150107054',
    projectId: 'lina-ad203',
    storageBucket: 'lina-ad203.firebasestorage.app',
    iosBundleId: 'bayserk.lina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFmF55dt5LNIY6sCFfcvrkpKFVpo2L2_M',
    appId: '1:146150107054:ios:2de9c8c247968eb9a28a3f',
    messagingSenderId: '146150107054',
    projectId: 'lina-ad203',
    storageBucket: 'lina-ad203.firebasestorage.app',
    iosBundleId: 'bayserk.lina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhkKXxts4_FmdJBZBLKpDE4DV7DsPPZkM',
    appId: '1:146150107054:web:13ccc61c620f772da28a3f',
    messagingSenderId: '146150107054',
    projectId: 'lina-ad203',
    authDomain: 'lina-ad203.firebaseapp.com',
    storageBucket: 'lina-ad203.firebasestorage.app',
    measurementId: 'G-DMCPR7V65Q',
  );
}
